<div className={`sidebar-option flex justify-center
    content-center group dark:text-white dark:bg-night-900`}>
    <div className='dark:text-white sidebar-icon flex content-center
    justify-center text-black group-hover:rotate-12 group-hover:translate-x-1
    group-hover:text-primaryStrong duration-100'>
        {icon}
    </div>
    
    <div className={`dark:text-white ml-5 font-semibold text-black
         group-hover:text-primaryStrong group-hover:translate-x-1 duration-100`}>
        {text}
    </div>
    
    <div className={`dark:text-white text-slate-500 ml-auto mr-4 `}>
        {number}
    </div>
</div>



